"use strict";

/*
 * Base de panneaux du code de la route français.
 * Chaque "code" correspond exactement au fichier Wikimedia Commons
 * "File:France road sign {code}.svg" (vérifié pour plusieurs entrées,
 * ex. A1a, C24a, C111...).
 * Sources : annexe de l'arrêté du 24 novembre 1967 (version consolidée
 * mars 2024, CEREMA), Wikipédia FR (listes officielles par type A / AB / B / C / CE).
 * Certains codes récents ou peu illustrés peuvent ne pas avoir d'image
 * disponible sur Wikimedia Commons : le jeu les ignore alors automatiquement
 * (fetchSignImageUrl renvoie null et un autre panneau est tiré à la place).
 *
 * Plusieurs codes peuvent légitimement partager le même "meaning" (ex. le
 * pictogramme vache/mouton pour "Passage d'animaux domestiques", ou le
 * panneau danger vs le panneau indication pour "Passage pour piétons").
 * Le jeu gère ça lui-même : en mode "trouve le panneau", n'importe quel
 * panneau ayant la même signification que celle affichée est accepté comme
 * bonne réponse (voir handleFindAnswer dans script.js). En revanche, dans
 * le QCM, pickDistractors() exclut les panneaux de même "meaning" de la
 * liste des mauvaises réponses, pour ne jamais afficher deux boutons avec
 * exactement le même texte.
 *
 * cat: "danger" | "priorite" | "interdiction" | "obligation" | "fin" | "zone" | "indication" | "service" | "temporaire"
 * Le champ "cat" est utilisé par pickDistractors() dans script.js pour
 * proposer des mauvaises réponses cohérentes (même famille de panneau).
 * "temporaire" regroupe les panneaux de danger temporaire (type AK, fond
 * jaune fluo) et de prescription temporaire (type KC), utilisés pour les
 * chantiers, accidents et autres dangers ponctuels sur la chaussée.
 */

const SIGNS = [
  // ---------- A — Panneaux de danger (30) ----------
  { code: "A1a", cat: "danger", meaning: "Virage à droite" },
  { code: "A1b", cat: "danger", meaning: "Virage à gauche" },
  { code: "A1c", cat: "danger", meaning: "Succession de virages dont le premier est à droite" },
  { code: "A1d", cat: "danger", meaning: "Succession de virages dont le premier est à gauche" },
  { code: "A2a", cat: "danger", meaning: "Cassis ou dos-d'âne" },
  { code: "A2b", cat: "danger", meaning: "Ralentisseur de type dos-d'âne" },
  { code: "A3", cat: "danger", meaning: "Chaussée rétrécie" },
  { code: "A3a", cat: "danger", meaning: "Chaussée rétrécie par la droite" },
  { code: "A3b", cat: "danger", meaning: "Chaussée rétrécie par la gauche" },
  { code: "A4", cat: "danger", meaning: "Chaussée particulièrement glissante" },
  { code: "A6", cat: "danger", meaning: "Pont mobile" },
  { code: "A7", cat: "danger", meaning: "Passage à niveau muni de barrières ou demi-barrières automatiques" },
  { code: "A8", cat: "danger", meaning: "Passage à niveau sans barrières ni demi-barrières" },
  { code: "A9a", cat: "danger", meaning: "Traversée de voie de véhicules de transport en commun" },
  { code: "A9b", cat: "danger", meaning: "Traversée de voies de tramway" },
  { code: "A13a", cat: "danger", meaning: "Endroit fréquenté par les enfants" },
  { code: "A13b", cat: "danger", meaning: "Annonce de passage(s) pour piétons" },
  { code: "A14", cat: "danger", meaning: "Autres dangers" },
  { code: "A15a1", cat: "danger", meaning: "Passage d'animaux domestiques" },
  { code: "A15a2", cat: "danger", meaning: "Passage d'animaux domestiques" },
  { code: "A15b", cat: "danger", meaning: "Passage d'animaux sauvages" },
  { code: "A15c", cat: "danger", meaning: "Passage de cavaliers" },
  { code: "A16", cat: "danger", meaning: "Descente dangereuse" },
  { code: "A17", cat: "danger", meaning: "Annonce de feux tricolores" },
  { code: "A18", cat: "danger", meaning: "Circulation dans les deux sens" },
  { code: "A19", cat: "danger", meaning: "Risque de chute de pierres" },
  { code: "A20", cat: "danger", meaning: "Débouché sur un quai ou une berge" },
  { code: "A21", cat: "danger", meaning: "Débouché de cyclistes venant de droite ou de gauche" },
  { code: "A23", cat: "danger", meaning: "Traversée d'une aire de danger aérien" },
  { code: "A24", cat: "danger", meaning: "Vent latéral" },

  // ---------- AB — Intersections et priorité (9) ----------
  { code: "AB1", cat: "priorite", meaning: "Priorité à droite" },
  { code: "AB2", cat: "priorite", meaning: "Priorité ponctuelle à la prochaine intersection" },
  { code: "AB3a", cat: "priorite", meaning: "Cédez le passage" },
  { code: "AB3b", cat: "priorite", meaning: "Signal avancé de cédez-le-passage" },
  { code: "AB4", cat: "priorite", meaning: "Stop" },
  { code: "AB5", cat: "priorite", meaning: "Signal avancé de stop" },
  { code: "AB6", cat: "priorite", meaning: "Route à caractère prioritaire" },
  { code: "AB7", cat: "priorite", meaning: "Fin de route à caractère prioritaire" },
  { code: "AB25", cat: "priorite", meaning: "Carrefour à sens giratoire" },

  // ---------- B — Panneaux d'interdiction (40) ----------
  { code: "B0", cat: "interdiction", meaning: "Circulation interdite à tout véhicule dans les deux sens" },
  { code: "B1", cat: "interdiction", meaning: "Sens interdit à tout véhicule" },
  { code: "B1j", cat: "interdiction", meaning: "Interdiction d'accès à contresens de bretelle de sortie" },
  { code: "B2a", cat: "interdiction", meaning: "Interdiction de tourner à gauche à la prochaine intersection" },
  { code: "B2b", cat: "interdiction", meaning: "Interdiction de tourner à droite à la prochaine intersection" },
  { code: "B2c", cat: "interdiction", meaning: "Interdiction de faire demi-tour" },
  { code: "B3", cat: "interdiction", meaning: "Interdiction de dépasser tous les véhicules à moteur (sauf deux-roues)" },
  { code: "B3a", cat: "interdiction", meaning: "Interdiction de dépasser pour les véhicules de plus de 3,5 tonnes" },
  { code: "B4", cat: "interdiction", meaning: "Arrêt au poste de douane" },
  { code: "B5a", cat: "interdiction", meaning: "Arrêt au poste de gendarmerie" },
  { code: "B5b", cat: "interdiction", meaning: "Arrêt au poste de police" },
  { code: "B5c", cat: "interdiction", meaning: "Arrêt au poste de péage" },
  { code: "B6a1", cat: "interdiction", meaning: "Stationnement interdit" },
  { code: "B6a2", cat: "interdiction", meaning: "Stationnement interdit du 1er au 15 du mois" },
  { code: "B6a3", cat: "interdiction", meaning: "Stationnement interdit du 16 à la fin du mois" },
  { code: "B6d", cat: "interdiction", meaning: "Arrêt et stationnement interdits" },
  { code: "B7a", cat: "interdiction", meaning: "Accès interdit aux véhicules à moteur, sauf cyclomoteurs" },
  { code: "B7b", cat: "interdiction", meaning: "Accès interdit à tous les véhicules à moteur" },
  { code: "B8", cat: "interdiction", meaning: "Accès interdit aux véhicules affectés au transport de marchandises" },
  { code: "B9a", cat: "interdiction", meaning: "Accès interdit aux piétons" },
  { code: "B9b", cat: "interdiction", meaning: "Accès interdit aux cycles" },
  { code: "B9c", cat: "interdiction", meaning: "Accès interdit aux véhicules à traction animale" },
  { code: "B9d", cat: "interdiction", meaning: "Accès interdit aux véhicules agricoles à moteur" },
  { code: "B9e", cat: "interdiction", meaning: "Accès interdit aux voitures à bras" },
  { code: "B9f", cat: "interdiction", meaning: "Accès interdit aux véhicules de transport en commun de personnes" },
  { code: "B9g", cat: "interdiction", meaning: "Accès interdit aux cyclomoteurs" },
  { code: "B9h", cat: "interdiction", meaning: "Accès interdit aux motocyclettes et motocyclettes légères" },
  { code: "B9i", cat: "interdiction", meaning: "Accès interdit aux véhicules tractant une caravane ou remorque de plus de 250 kg" },
  { code: "B10a", cat: "interdiction", meaning: "Accès interdit aux véhicules dont la longueur dépasse le nombre indiqué" },
  { code: "B11", cat: "interdiction", meaning: "Accès interdit aux véhicules dont la largeur dépasse le nombre indiqué" },
  { code: "B12", cat: "interdiction", meaning: "Accès interdit aux véhicules dont la hauteur dépasse le nombre indiqué" },
  { code: "B13", cat: "interdiction", meaning: "Accès interdit aux véhicules dont le poids total dépasse le nombre indiqué" },
  { code: "B13a", cat: "interdiction", meaning: "Accès interdit aux véhicules dont le poids par essieu dépasse le nombre indiqué" },
  { code: "B14", cat: "interdiction", meaning: "Limitation de vitesse" },
  { code: "B15", cat: "interdiction", meaning: "Cédez le passage à la circulation venant en sens inverse" },
  { code: "B16", cat: "interdiction", meaning: "Signaux sonores interdits" },
  { code: "B17", cat: "interdiction", meaning: "Interdiction de circuler sans maintenir un intervalle minimal entre véhicules" },
  { code: "B18a", cat: "interdiction", meaning: "Accès interdit aux véhicules transportant des marchandises explosives ou inflammables" },
  { code: "B18b", cat: "interdiction", meaning: "Accès interdit aux véhicules transportant des marchandises polluantes pour l'eau" },
  { code: "B18c", cat: "interdiction", meaning: "Accès interdit aux véhicules transportant des matières dangereuses" },
  { code: "B19", cat: "interdiction", meaning: "Autre interdiction précisée par une inscription sur le panneau" },

  // ---------- B — Panneaux d'obligation (18) ----------
  { code: "B21-1", cat: "obligation", meaning: "Obligation de tourner à droite avant le panneau" },
  { code: "B21-2", cat: "obligation", meaning: "Obligation de tourner à gauche avant le panneau" },
  { code: "B21a1", cat: "obligation", meaning: "Contournement obligatoire par la droite" },
  { code: "B21a2", cat: "obligation", meaning: "Contournement obligatoire par la gauche" },
  { code: "B21b", cat: "obligation", meaning: "Direction obligatoire à la prochaine intersection : tout droit" },
  { code: "B21c1", cat: "obligation", meaning: "Direction obligatoire à la prochaine intersection : à droite" },
  { code: "B21c2", cat: "obligation", meaning: "Direction obligatoire à la prochaine intersection : à gauche" },
  { code: "B21d1", cat: "obligation", meaning: "Directions obligatoires : tout droit ou à droite" },
  { code: "B21d2", cat: "obligation", meaning: "Directions obligatoires : tout droit ou à gauche" },
  { code: "B21e", cat: "obligation", meaning: "Directions obligatoires : à droite ou à gauche" },
  { code: "B22a", cat: "obligation", meaning: "Piste ou bande obligatoire pour les cycles" },
  { code: "B22b", cat: "obligation", meaning: "Chemin obligatoire réservé aux piétons" },
  { code: "B22c", cat: "obligation", meaning: "Chemin obligatoire réservé aux cavaliers" },
  { code: "B25", cat: "obligation", meaning: "Vitesse minimale obligatoire" },
  { code: "B26", cat: "obligation", meaning: "Chaînes à neige obligatoires sur au moins deux roues motrices" },
  { code: "B27a", cat: "obligation", meaning: "Voie réservée aux véhicules de transport en commun" },
  { code: "B27b", cat: "obligation", meaning: "Voie réservée aux tramways" },
  { code: "B29", cat: "obligation", meaning: "Autre obligation précisée par une inscription sur le panneau" },

  // ---------- B — Fin d'interdiction / fin d'obligation (13) ----------
  { code: "B31", cat: "fin", meaning: "Fin de toutes les interdictions précédemment signalées" },
  { code: "B33", cat: "fin", meaning: "Fin de limitation de vitesse" },
  { code: "B34", cat: "fin", meaning: "Fin d'interdiction de dépasser (panneau B3)" },
  { code: "B34a", cat: "fin", meaning: "Fin d'interdiction de dépasser (panneau B3a)" },
  { code: "B35", cat: "fin", meaning: "Fin d'interdiction de l'usage de l'avertisseur sonore" },
  { code: "B39", cat: "fin", meaning: "Fin d'une interdiction précisée par une inscription sur le panneau" },
  { code: "B40", cat: "fin", meaning: "Fin de piste ou bande obligatoire pour cycles" },
  { code: "B41", cat: "fin", meaning: "Fin de chemin obligatoire pour piétons" },
  { code: "B42", cat: "fin", meaning: "Fin de chemin obligatoire pour cavaliers" },
  { code: "B43", cat: "fin", meaning: "Fin de vitesse minimale obligatoire" },
  { code: "B44", cat: "fin", meaning: "Fin d'obligation de l'usage des chaînes à neige" },
  { code: "B45", cat: "fin", meaning: "Fin de voie réservée aux transports en commun" },
  { code: "B49", cat: "fin", meaning: "Fin d'une obligation précisée par une inscription sur le panneau" },

  // ---------- B — Prescription zonale (20) ----------
  { code: "B6b1", cat: "zone", meaning: "Entrée d'une zone à stationnement interdit" },
  { code: "B6b2", cat: "zone", meaning: "Entrée d'une zone à stationnement unilatéral à alternance semi-mensuelle" },
  { code: "B6b3", cat: "zone", meaning: "Entrée d'une zone à stationnement de durée limitée avec disque" },
  { code: "B6b4", cat: "zone", meaning: "Entrée d'une zone à stationnement payant" },
  { code: "B6b5", cat: "zone", meaning: "Entrée d'une zone à stationnement alterné et limité, avec disque" },
  { code: "B30", cat: "zone", meaning: "Entrée d'une zone à vitesse limitée à 30 km/h" },
  { code: "B50a", cat: "zone", meaning: "Sortie de zone à stationnement interdit" },
  { code: "B50b", cat: "zone", meaning: "Sortie de zone à stationnement unilatéral à alternance semi-mensuelle" },
  { code: "B50c", cat: "zone", meaning: "Sortie d'une zone à stationnement de durée limitée avec disque" },
  { code: "B50d", cat: "zone", meaning: "Sortie de zone à stationnement payant" },
  { code: "B50e", cat: "zone", meaning: "Sortie d'une zone à stationnement alterné et limité, avec disque" },
  { code: "B51", cat: "zone", meaning: "Sortie d'une zone à vitesse limitée à 30 km/h" },
  { code: "B52", cat: "zone", meaning: "Entrée d'une zone de rencontre" },
  { code: "B53", cat: "zone", meaning: "Sortie d'une zone de rencontre" },
  { code: "B54", cat: "zone", meaning: "Entrée d'une aire piétonne" },
  { code: "B55", cat: "zone", meaning: "Sortie d'une aire piétonne" },
  { code: "B56", cat: "zone", meaning: "Entrée de zone de circulation restreinte" },
  { code: "B57", cat: "zone", meaning: "Sortie de zone de circulation restreinte" },
  { code: "B58", cat: "zone", meaning: "Entrée de zone d'obligation d'équipements en période hivernale" },
  { code: "B59", cat: "zone", meaning: "Sortie de zone d'obligation d'équipements en période hivernale" },

  // ---------- C — Panneaux d'indication ----------
  { code: "C1a", cat: "indication", meaning: "Lieu aménagé pour le stationnement" },
  { code: "C1b", cat: "indication", meaning: "Lieu aménagé pour le stationnement gratuit à durée limitée" },
  { code: "C1c", cat: "indication", meaning: "Lieu aménagé pour le stationnement payant" },
  { code: "C3", cat: "indication", meaning: "Risque d'incendie" },
  { code: "C4a", cat: "indication", meaning: "Vitesse conseillée" },
  { code: "C4b", cat: "indication", meaning: "Fin de vitesse conseillée" },
  { code: "C5", cat: "indication", meaning: "Station de taxis" },
  { code: "C6", cat: "indication", meaning: "Arrêt d'autobus" },
  { code: "C8", cat: "indication", meaning: "Emplacement d'arrêt d'urgence" },
  { code: "C9", cat: "indication", meaning: "Station d'autopartage" },
  { code: "C12", cat: "indication", meaning: "Circulation à sens unique" },
  { code: "C13a", cat: "indication", meaning: "Impasse" },
  { code: "C13b", cat: "indication", meaning: "Présignalisation d'une impasse" },
  { code: "C13c", cat: "indication", meaning: "Impasse avec issue pour piétons" },
  { code: "C13d", cat: "indication", meaning: "Impasse avec issue pour piétons et cyclistes" },
  { code: "C18", cat: "indication", meaning: "Priorité par rapport à la circulation venant en sens inverse" },
  { code: "C20a", cat: "indication", meaning: "Indication d'un passage pour piétons" },
  { code: "C20b", cat: "indication", meaning: "Traversée de voie de transport en commun" },
  { code: "C20c", cat: "indication", meaning: "Traversée de voies de tramway" },
  { code: "C23", cat: "indication", meaning: "Stationnement réglementé pour caravanes et autocaravanes" },
  { code: "C25a", cat: "indication", meaning: "Limites de vitesse en France, aux frontières" },
  { code: "C25b", cat: "indication", meaning: "Rappel des limites de vitesse sur autoroute" },
  { code: "C26a", cat: "indication", meaning: "Voie de détresse à droite" },
  { code: "C26b", cat: "indication", meaning: "Voie de détresse à gauche" },
  { code: "C27", cat: "indication", meaning: "Surélévation de chaussée" },
  { code: "C28", cat: "indication", meaning: "Réduction du nombre de voies sur route à chaussées séparées" },
  { code: "C29a", cat: "indication", meaning: "Présignalisation d'un créneau de dépassement" },
  { code: "C30", cat: "indication", meaning: "Fin d'un créneau de dépassement à trois voies" },
  { code: "C107", cat: "indication", meaning: "Début d'une route à accès réglementé" },
  { code: "C108", cat: "indication", meaning: "Fin de route à accès réglementé" },
  { code: "C111", cat: "indication", meaning: "Entrée d'un tunnel" },
  { code: "C112", cat: "indication", meaning: "Sortie de tunnel" },
  { code: "C113", cat: "indication", meaning: "Piste ou bande cyclable conseillée et réservée aux cycles" },
  { code: "C114", cat: "indication", meaning: "Fin de piste ou bande cyclable conseillée" },
  { code: "C115", cat: "indication", meaning: "Voie verte, réservée aux piétons et véhicules non motorisés" },
  { code: "C116", cat: "indication", meaning: "Fin de voie verte" },
  { code: "C207", cat: "indication", meaning: "Début d'une section d'autoroute" },
  { code: "C208", cat: "indication", meaning: "Fin d'une section d'autoroute" },

  // ---------- CE — Panneaux de service ----------
  { code: "CE1", cat: "service", meaning: "Poste de secours" },
  { code: "CE2a", cat: "service", meaning: "Poste d'appel d'urgence" },
  { code: "CE2b", cat: "service", meaning: "Cabine téléphonique publique" },
  { code: "CE3a", cat: "service", meaning: "Informations touristiques" },
  { code: "CE4a", cat: "service", meaning: "Terrain de camping pour tentes" },
  { code: "CE4b", cat: "service", meaning: "Terrain de camping pour caravanes et autocaravanes" },
  { code: "CE4c", cat: "service", meaning: "Terrain de camping pour tentes, caravanes et autocaravanes" },
  { code: "CE5a", cat: "service", meaning: "Auberge de jeunesse" },
  { code: "CE5b", cat: "service", meaning: "Chambre d'hôtes ou gîte" },
  { code: "CE6a", cat: "service", meaning: "Point de départ d'un itinéraire pédestre" },
  { code: "CE6b", cat: "service", meaning: "Point de départ d'un circuit de ski de fond" },
  { code: "CE7", cat: "service", meaning: "Emplacement pour pique-nique" },
  { code: "CE8", cat: "service", meaning: "Gare auto/train" },
  { code: "CE9", cat: "service", meaning: "Parc de stationnement sous vidéoprotection" },
  { code: "CE10", cat: "service", meaning: "Embarcadère" },
  { code: "CE12", cat: "service", meaning: "Toilettes ouvertes au public" },
  { code: "CE14", cat: "service", meaning: "Installations accessibles aux personnes à mobilité réduite" },
  { code: "CE15a", cat: "service", meaning: "Poste de distribution de carburant ouvert 24h/24, 7j/7" },
  { code: "CE15g", cat: "service", meaning: "Poste de carburant 24h/24 assurant la recharge des véhicules électriques" },
  { code: "CE15i", cat: "service", meaning: "Poste de recharge de véhicules électriques ouvert 24h/24, 7j/7" },
  { code: "CE16", cat: "service", meaning: "Restaurant" },
  { code: "CE17", cat: "service", meaning: "Hôtel ou motel" },
  { code: "CE18", cat: "service", meaning: "Débit de boissons ou collations" },
  { code: "CE19", cat: "service", meaning: "Mise à l'eau d'embarcations légères" },
  { code: "CE20a", cat: "service", meaning: "Gare de téléphérique" },
  { code: "CE20b", cat: "service", meaning: "Point de départ d'un télésiège ou d'une télécabine" },
  { code: "CE21", cat: "service", meaning: "Point de vue" },
  { code: "CE23", cat: "service", meaning: "Jeux d'enfants" },
  { code: "CE24", cat: "service", meaning: "Station de vidange pour caravanes et autocaravanes" },
  { code: "CE25", cat: "service", meaning: "Distributeur de billets de banque" },
  { code: "CE26", cat: "service", meaning: "Station de gonflage gratuite" },
  { code: "CE27", cat: "service", meaning: "Point de détente" },
  { code: "CE28", cat: "service", meaning: "Poste de dépannage" },
  { code: "CE29", cat: "service", meaning: "Moyen de lutte contre l'incendie" },
  { code: "CE30a", cat: "service", meaning: "Issue de secours vers la droite" },
  { code: "CE30b", cat: "service", meaning: "Issue de secours vers la gauche" },
  { code: "CE52", cat: "service", meaning: "Lieu aménagé pour la pratique du covoiturage" },

  // ---------- AK — Panneaux de danger temporaire (chantiers, accidents) ----------
  { code: "AK2", cat: "temporaire", meaning: "Cassis ou dos-d'âne" },
  { code: "AK3", cat: "temporaire", meaning: "Chaussée rétrécie" },
  { code: "AK4", cat: "temporaire", meaning: "Chaussée glissante" },
  { code: "AK5", cat: "temporaire", meaning: "Travaux" },
  { code: "AK14", cat: "temporaire", meaning: "Autres dangers" },
  { code: "AK17", cat: "temporaire", meaning: "Annonce de feux tricolores réglant la circulation" },
  { code: "AK22", cat: "temporaire", meaning: "Projection de gravillons" },
  { code: "AK30", cat: "temporaire", meaning: "Bouchon" },
  { code: "AK31", cat: "temporaire", meaning: "Accident" },
  { code: "AK32", cat: "temporaire", meaning: "Nappes de brouillard ou de fumées épaisses" },

  // ---------- KC — Panneaux de prescription temporaire (chantiers) ----------
  { code: "KC1", cat: "temporaire", meaning: "Route barrée" },
];
